### ISSUE TITLE
Support L4D1 Windows?

### ISSUE THREAD

**Issue by fbef0102** [L4D-Community/Collisionhook#2]
Download and install latest build "L4D2Collisionhook-sm1.11-win-e6890bf" in "Actions" page, but errors in l4d1 windows

* sm version
  ```php
  SourceMod Version: 1.11.0.6919
  ```

* meta version
  ```php
  Metamod:Source version 1.11.0-dev+1148
  ```

* error
  ```php
  L 01/13/2023 - 03:03:52: [CLHOOK] Sigscan for PassServerEntityFilter failed
  L 01/13/2023 - 03:03:52: [SM] Unable to load extension "collisionhook.ext.2.l4d": Unable to hook PassServerEntityFilter!
  ```

If I use [l4d1_signatures from Psykotikism](https://github.com/Psykotikism/L4D1-2_Signatures/blob/main/l4d1/gamedata/l4d1_signatures.txt#L4414-L4421), server crash 
* Crash ID: [2D4M-DPPT-AJ67](https://crash.limetech.org/2d4mdpptaj67)
Raw: [2D4M-DPPT-AJ67.txt](https://github.com/L4D-Community/Collisionhook/files/10405246/2D4M-DPPT-AJ67.txt)

**Comment by A1mDev** [comment]
You will get a crash because github actions only builds extension for game left4dead2. if before it didn't affect anything, now it does because of 2 extra parameters in CollisinEvent::ShouldCollide in l4d2 left4dead2. I checked left4dead1 (linux) there are no extra parameters in this function. So you will have to build by yourself until i added the build for other games in github actions.

Linux signature:
```_ZN15CCollisionEvent13ShouldCollideEP14IPhysicsObjectS1_PvS2_```
```CCollisionEvent::ShouldCollide(IPhysicsObject *,IPhysicsObject *,void *,void *)```

**Comment by A1mDev** [comment]
Try now for windows it builds successfully, for linux for some reason it doesn't, apparently there is a problem with github actions, it will need to be built later.

**Comment by fbef0102** [comment]
Test Left 4 Dead 1 linux server today, this extension conflicts with [Accelerator - Crash Reporting That Doesn't Suck](https://forums.alliedmods.net/showthread.php?t=277703),

If acceleator tries to upload last time crash dumps when server launches, the server crashes
```c
Executing dedicated server config file
Wrote minidump to: /root/sv1/left4dead/addons/sourcemod/data/dumps/4debde98-32a5-4a75-13ee5bb4-996e80a0.dmp
Segmentation fault (core dumped)
cat: hlds.19866.pid: No such file or directory
email debug.log to linux@valvesoftware.com
Sun Jan 15 02:14:32 CST 2023: Server restart in 10 seconds
Sun Jan 15 02:14:35 CST 2023: Server Quit
```
* crash ID: [4KT4-WWLG-DI7P](https://crash.limetech.org/4kt4wwlgdi7p)
  * [4KT4-WWLG-DI7P.txt](https://github.com/L4D-Community/Collisionhook/files/10418536/4KT4-WWLG-DI7P.txt)


Here is my linux version
```c
Description:    Ubuntu 18.04.4 LTS
```

**Comment by A1mDev** [comment]
Did you download the latest version of accelerator for linux (2.5.0-cd575aa)?

**Comment by fbef0102** [comment]
> Did you download the latest version of accelerator for linux (2.5.0-cd575aa)?
Yes
```c
 File: accelerator.ext.so
 Loaded: Yes (version 2.5.0)
 Name: Accelerator (SRCDS Crash Handler)
 Author: Asher "asherkin" Baker (https://crash.limetech.org/)
 Binary info: API version 8 (compiled Jul 27 2019)
 Method: Loaded by SourceMod
 ```

**Comment by A1mDev** [comment]
Well, this is clearly not related to my code, rather some kind of incompatibility with the new clang compiler. This means that you will face the same problem with other expansions if they are built on the new clang compiler. Probably extension accelerator can't read some symbols from extension collisionhook. I think it is necessary to rebuild or fix the accelerator extension or downgrade clang version?!

**Comment by A1mDev** [comment]
@fbef0102, try the latest version, let me know if there are any problems.

**Comment by fbef0102** [comment]
> @fbef0102, try the latest version, let me know if there are any problems.

Unfortunately, the constant crash still happenes

**Comment by A1mDev** [comment]
What crash do you mean?

**Comment by fbef0102** [comment]
step to reproduce in linux system

1. install collisionhook
2. install accelerator 
3. first time launch server 
4. type
```
sm_cvar sv_cheats 1
crash
````
5. acceleator wrote minidump to: /root/sv1/left4dead/addons/sourcemod/data/dumps/xxxxxxxxx.dmp
6. auto restart server in linux (2nd time  launch server)
7. acceleator tries to upload dump log -> crash -> acceleator wrote minidump to: /root/sv1/left4dead/addons/sourcemod/data/dumps/xxxxxxxxx.dmp
8. auto restart server in linux (3rd time  launch server)
9. acceleator tries to upload dump log -> crash -> acceleator wrote minidump to: /root/sv1/left4dead/addons/sourcemod/data/dumps/xxxxxxxxx.dmp
10. auto restart server in linux (4th time  launch server)
11. acceleator tries to upload dump log -> crash -> acceleator wrote minidump to: /root/sv1/left4dead/addons/sourcemod/data/dumps/xxxxxxxxx.dmp
12. ......

**Comment by A1mDev** [comment]
I think you'd better write to the author of this extension, since it has nothing to do with this repository. I wrote an empty test extension that contains almost nothing and crash happens too (on an empty server), which means that any extension built on a new compiler will crash, if you have the accelerator extension installed. Compiler flag '-gdwarf-4' also solves this problem, but I don't know if it's a good idea.

**Comment by fbef0102** [comment]
Right, thanks for your work.
