### ISSUE TITLE
[Crash] CS: GO Windows server

### ISSUE THREAD

**Issue by ELDment** [L4D-Community/Collisionhook#3]
**Crash on SRCDS startup.**
No longer crashes after deleting the eg. plugin (Compile with sm1.11)

**Comment by vikingo12** [comment]
did you just post an issue about csgo in l4d repository?

**Comment by ELDment** [comment]
> did you just post an issue about csgo in l4d repository?

![image](https://github.com/L4D-Community/Collisionhook/assets/79680886/96c61901-60cc-4090-8362-a224933f596c)
**What's this?**

**Comment by A1mDev** [comment]
> **Crash on SRCDS startup.** No longer crashes after deleting the eg. plugin (Compile with sm1.11)

Problem solved, could you test it?
